#!/bin/bash

function solucionar_rompecabezas {
    var_A=1
    var_B=1
    var_C=1
    var_D=1

    for (( i=1; i<=$1; i++ )); do
        resultado=$((3 * var_D + 1 * var_C + 4 * var_B + 1 * var_A))
        var_A=$var_B
        var_B=$var_C
        var_C=$var_D
        var_D=$resultado
    done

    echo $(($var_D % 10000000000)) # últimos 10 dígitos de var_D
}

solucionar_rompecabezas 10
echo
solucionar_rompecabezas 100
echo
result=$(echo "2^3" | bc)
solucionar_rompecabezas $result # 2023 elevado a la 100
